from setuptools import setup, find_packages

setup(
    name="gigapath-wsi-analysis",
    version="0.1.0",
    description="GigaPath AI WSI Breast Cancer Lesion Analysis with Top-K Sampling",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.21.0",
        "openslide-python>=1.2.0",
        "h5py>=3.7.0",
        "PyYAML>=6.0",
        "tqdm>=4.64.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.12.0",
        "scikit-learn>=1.0.0",
        "Pillow>=9.0.0",
        "opencv-python>=4.7.0",
        "pandas>=1.4.0",
        "tensorboard>=2.11.0",
        "timm>=0.9.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
